os: linux
sudo: required
addons:
  apt:
    packages:
      - pass
services:
- docker
before_install:
- docker build -t music-box-test . --build-arg TAG_ID=chapman
script:
- docker run -it music-box-test bash -c 'cd /build; make test'
deploy:
  provider: script
  script: bash docker_push
  on:
    branch: release
notifications:
  slack:
    rooms:
      secure: ieV9kSzrj6BkCLx81XM4XTjne+EdYLVnHufCkVSsLFmvABOu3rcla0uzfnTcLBdp7TbGctXzLBYUUBeMYLgxeE69JeqBSYx7BGO3KiA/27bBp5b8Mq+K7orNoCFJ8UV8iYl5eg3Qx2a9CBWD+yMVi7MCSgdYRDaQn/3JV5PFBKJnWlAI4cszGC3Gr0sKNSvqONkXWBy1Ua+3PGRBbG0zZdXYZd0LVO9omW30oxL2omdCeozZrHMpNLCP7zKy8bOIxYC4HQieewvQdPw3XmwmDU5fSW7whNfcAbIL/Jn7vRmpuUZr+EDx5rabMifb8qYTuWHkoDmvxR/ZxaYsNeQ9QfBXAzhit/cxgFPDWdrfVlkSV7vS2H1aSFv5+DLedOCZgKeXVJhZ115eDiVPtb1OSkvUc3I5TqtfwuJQaajdfFMSvFrkjNY6/UGbStb+nglFbr95MNqMuRRnPnZ5UOaPiAiStCl0+TuYExUFxKSK/nVhHdwr9cfBT9W9lyBK5hY1CysMqe+Bxi07ijxpTeCdnz7+hM3zGeoWGCz9g2JLb+fRzuHxLDtWqa5jrVjyZ1Jp8wG28QbWvfwMdAoFtB/7DOcqKXAOvSSVQ7I9QCOpzZ6/nA4sTLIlwSjr9cjO+/SzRTqA8fuD9WuogjB5Tfy1xdYLOVzPqUQwiH2Z+8s2uCI=
