FROM fedora:37

RUN dnf -y update \
    && dnf -y install \
        git \
        gcc \
        gcc-c++ \
        make \
        python3-devel \
        python3-pip \
    && dnf clean all

COPY . /music-box/

WORKDIR /music-box

RUN pip3 install -e .

ARG SUFFIX=""
ENV SWITCHER_SUFFIX=$SUFFIX

RUN echo "The suffix is '$SWITCHER_SUFFIX'"

RUN cd docs \
    && pip3 install -r requirements.txt \
    && make html