FROM fedora:37

RUN dnf -y update \
    && dnf -y install \
        git \
        gcc \
        gcc-c++ \
        gfortran \
        lapack-devel \
        make \
        netcdf-fortran-devel \
        nodejs \
        npm \
        pandoc \
        python3-devel \
        python3-pip \
    && dnf clean all

COPY . /music-box/

WORKDIR /music-box

RUN npm install

RUN pip3 install -e .[doc]

RUN cd docs && make html

