name: build

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: build Docker image
      run: docker build -t music-box-test . --build-arg TAG_ID=chapman
    - name: run tests in container
      run: docker run --name test-container -t music-box-test bash -c 'cd /music-box/build; make test'
